### ISSUE TITLE
[Epic] Create testing package for WebDriverIO

### ISSUE THREAD

**Issue by StephenEsser** [cerner/terra-toolkit#401]
# Feature Request

Create a new [WebDriverIO](https://webdriver.io/) testing package using [WDIO 6](https://webdriver.io/blog/2020/03/26/webdriverio-v6-released.html).

This issue will be treated as an Epic to be closed after the initial release of the package. There will be multiple issues created to move the enhancements into smaller pieces.
 
## Description

The existing WebDriver testing infrastructure is using WDIO 4 and an unmaintained [visual regression service](https://github.com/zinserjan/wdio-visual-regression-service). The new package should utilize the latest available WebDriverIO and accessibility (axe-core) packages and carry forward the necessary customization options.

An upgrade guide and transition strategy should be included with these changes.

## Notes

This section will be used to document various conversations that happen during development.

[When running on CI the maxInstances for the WDIO configuration needs to be set to one.](https://github.com/cerner/terra-toolkit/pull/406#discussion_r420932255)

## Breaking Changes

- WDIO 6 has several breaking changes for global/browser command execution
- ~The [selenium docker](https://github.com/SeleniumHQ/docker-selenium) images have been updated to the latest available~
- The timezone is now going to default to the zone provided by the docker image. See https://github.com/cerner/terra-toolkit-boneyard/issues/7 for additional details. Related discussion can be found [here](https://github.com/cerner/terra-toolkit/pull/412#discussion_r433853080).
- Axe core has been updated to the latest available version which introduced a few bug fixes that may break existing tests
- Removed the `Terra.it` commands
- Removed the global `browser.axe` command

## Additions

- The Selenium Docker Service accepts a configurable version of selenium to test against various images.

## Subtasks

- [x] [Initialize terra-functional-testing package](https://github.com/cerner/terra-toolkit/pull/403)
- [x] [Add Initial WDIO 6 test runner](https://github.com/cerner/terra-toolkit/issues/405)
- [x] [Add Docker Service](https://github.com/cerner/terra-toolkit/issues/410)
- [X] [Add Axe Integration](https://github.com/cerner/terra-toolkit/pull/416)
- [X] [Add Asset Server Service](https://github.com/cerner/terra-toolkit/pull/417)
- [x] [Add documentation for each of the available testing environment variable overrides](https://github.com/cerner/terra-toolkit/issues/528) - Stephen Esser
- [x] [Add Terra WDIO Reporter](https://github.com/cerner/terra-toolkit/issues/527) - Stephen Esser
- [x] Add Terra Accessibility Reporter - Stephen Esser - Added in PR https://github.com/cerner/terra-toolkit/pull/456
- [x] [Use latest axe core version](https://github.com/cerner/terra-toolkit/issues/426)
- [x] [Remove custom TZ on deploy WDIO grid](#425)
- [x] Setup and test internally against the grid
- [x] [Add Terra Service](https://github.com/cerner/terra-toolkit/issues/413)
  - [x] Add Terra viewports - [PR](https://github.com/cerner/terra-toolkit/pull/438) - Ben Cai
  - [x] Add Terra.validates.accessibility command
  - [x] Add Terra.validates.screenshot command - Ben Cai
  - [x] Add Terra.validates.element command - Ben Cai
  - [x] Add API and reporter for warning on new axe-core rules - Stephen Esser
  - [x] Add deprecation warning to terra-toolkit-boneyard for it matchers - [PR](https://github.com/cerner/terra-toolkit-boneyard/pull/64) - Ben Cai
- [ ] Uplift Repositories to WDIO 6
  - [x] [Terra Core](https://github.com/cerner/terra-core/issues/3320)
  - [X] [Terra Framework](https://github.com/cerner/terra-framework/pull/1382)
  - [X] [Terra Clinical](https://github.com/cerner/terra-clinical/pull/749)
  - [x] Terra Application [#125](https://github.com/cerner/terra-application/issues/125) & [#126](https://github.com/cerner/terra-application/issues/126)
  - [ ] [Terra Dev Site](https://github.com/cerner/terra-dev-site/issues/326)
- [ ] Add Visual Regression Service - [PR](https://github.com/cerner/terra-toolkit/pull/430)
    - [ ] Fail VR if new reference screenshot is created during CI run (similar to https://github.com/cerner/terra-toolkit-boneyard/issues/21 && https://github.com/zinserjan/wdio-visual-regression-service/issues/83). https://github.com/cerner/terra-toolkit/issues/603 logged to terra-functional-testing.
   - [x] [Fix x / y out of bounds error](https://github.com/zinserjan/wdio-screenshot/issues/66) commonly seen when element is larger than the viewport (similar to https://github.com/zinserjan/wdio-screenshot/issues/87) 
   - [x] Generate a diff screenshot if the latest screenshot is larger than the reference screenshot - Emily
   - [x] Simplify configuration - Emily
- [X] Migration Guide - In progress on PR https://github.com/cerner/terra-toolkit/pull/574

## Side Quests

- [x] Terra CLI - created in PR https://github.com/cerner/terra-toolkit/pull/460
- [x] [Automatically detect IP address for use on VPN](https://github.com/cerner/terra-toolkit/pull/564)
- [x] [Improve Logger functionality](https://github.com/cerner/terra-toolkit/issues/414)
- [ ] Improve VR error log message to include the screenshot name for quicker tracing when it fails.

## Spikes

- [X] [Investigate an easier API for overriding/customizing the wdio configuration](https://github.com/cerner/terra-toolkit/pull/583)
- [ ] Using [Page objects](https://webdriver.io/docs/pageobjects.html)
~- Using the latest selenium images~
- [ ] Using the non-headless chrome
- [ ] [Including a configuration argument for webpack file path](https://github.com/cerner/terra-toolkit/issues/604)
- [X] [Obsolete screenshot flags similar to jest for updating screenshots](https://github.com/cerner/terra-toolkit/pull/568)
- [X] [Visual regression services](https://github.com/cerner/terra-toolkit/pull/430)

**Comment by emilyrohrbough** [comment]
Recently there was discussion that the selenium-docker image change would not be made in this Major Version Bump.

@StephenEsser reverted the selenium-docker image change in PR https://github.com/cerner/terra-toolkit/pull/472.

I have updated the issue summary to remove the work related to this change.
